# Source files for XLMRoberta application
xlm_roberta_src = [
    meson.current_source_dir() / 'xlm_roberta.cpp',
    meson.current_source_dir() / 'position.cpp',
    meson.current_source_dir() / 'token_type.cpp',
    meson.current_source_dir() / 'util.cpp',
    meson.current_source_dir() / 'fc_layer_single.cpp',
]

xlm_roberta_inc = include_directories('.')

causallm_src += xlm_roberta_src
causallm_inc += xlm_roberta_inc
